apiVersion: apps/v1
kind: Deployment
metadata:
  name: hack-frontend
  namespace: hack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hack-frontend
  template:
    metadata:
      labels:
        app: hack-frontend
    spec:
      containers:
      - name: frontend
        # A imagem será definida pelo kustomize edit set image no CI/CD
        image: frontend-image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"