name: CI/CD Frontend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: hack-frontend
  EKS_CLUSTER_NAME: hack-infra-eks
  DEPLOYMENT_NAME: hack-frontend
  CONTAINER_NAME: frontend
  K8S_NAMESPACE: hack-frontend

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 1. Configura Credenciais AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    # 2. Login no Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 3. Build e Push da Imagem Docker
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build da imagem
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        # Push para o ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Salva a imagem na saída para o próximo passo usar
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    # 4. Instala o Kustomize
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2

    # 5. Deploy usando Kustomize
    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        
        cd k8s
        
        # Define a imagem correta
        kustomize edit set image frontend-image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Gera e aplica tudo (Namespace, Deployment, Service, Ingress) de uma vez
        kustomize build . | kubectl apply -f -
        
        # Aguarda o rollout no namespace correto
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n ${{ env.K8S_NAMESPACE }}